{% set name = "hyperspy-gui-traitsui" %}
{% set filename = "hyperspy_gui_traitsui" %}
{% set version = "1.5.1" %}
{% set sha256 = "74976396e234be3487bd9a1603cf4de539cfa2663f0d296d09ac326b8fe44228" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - pyqt
    - traits >=5.0
    - traitsui >=6.1
    - hyperspy-base >=1.7.0

test:
  imports:
    - hyperspy_gui_traitsui


about:
  home: https://github.com/hyperspy/hyperspy_gui_traitsui
  license: GPL-3.0-or-later
  summary: traitsui GUI elements for HyperSpy.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
    - ericpre
