{% set name = "hyperspy-gui-traitsui" %}
{% set filename = "hyperspy_gui_traitsui" %}
{% set version = "2.1.1" %}
{% set sha256 = "9818940aa0cf67640b862b23d824da9b6fe7c2d87f2d4e3068aa974e77ecd0d8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >=8

  run:
    - python >={{ python_min }}
    - traits >=6.3
    - traitsui >=8.0
    - hyperspy-base >=2.3.0

test:
  imports:
    - hyperspy_gui_traitsui
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyperspy/hyperspy_gui_traitsui
  license: GPL-3.0-or-later
  summary: traitsui GUI elements for HyperSpy.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
    - ericpre
