travis:
  secure:
    BINSTAR_TOKEN: cpuAwaT7t8VyFdiWYYwFGgWAkl/k6WGBWMxy6C6uCi1aXT+vOioZNRUaky2gj8x1am7KrT6Kznzr35fg1DqgAjMpA5FFbeQMXrC0A3JmG9s8SNS9+DRF2L5adJj3tQ9HUK4TNfAcadScdyNiAMsquhCxWSbSvaDpvIlp7Nf4MFNyRpp2CC719AtKKRxTY57x2w42xZrIoffqCc5fBgvNAV0jIQu3llJPPULVedtx4W6+lvt5Ra8P3516oK9kueYWtnfvG343d8DcgYdd/eCz59yU8GTEnf1P0JZ+jkDS6RqsEacBPQyGj8zWegpYGURazMm+qLY8vnhBvA0CF3WBBMiWT+ZWI2jfsYW1tYKJkOfa325UerqYuPJ5z0ABCuTra5VAkefx//VIuTzn4Qm+dE+n7H4OzvmHucCLCaD0TFcLw1KH8YyIRSwKk2dPF8dqn4CRIuwpdjLt2RRBS0fRB6o47cvupHy0PCmCWihrfL4KUw2KKpND72PqobaqxFJ1P0lyiIVW2FcnUmojB6VmvL7tQmDI2P/P4XhkzeTA24y5JVSMcWLvSZHNv6ZZ3lmyc+18lXa6iGgqXHGpZpC9QM/3tYuu2Bcs6AB/wkUpkGYXKOEcUXQRPqEkTdcYP2IAYHiDvWT7iWA+paSVvIm/N1chbROPPluYhIfb7+YXl44=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
