travis:
  secure:
    BINSTAR_TOKEN: pbfjCeob2k3FllpFzIwvo/kQsjNMyz1tIhsXnmNBb2hH4Tyc/f7WZsQ6omE5s7r06jy1O67W4dL+E4hX+Y0hDGePEagi2pmHSM8qGPUWl71pAsAYbCDs3p2UoMZHFbemrSw+TIhmX2egq3IKZBvzeO3B2CVcDlqR3e9HCWVETFTRmPTnhARtx04fHLEQWXfQHk9twdMdhA6mSDlY8L4UEGqgHxUMmBa7oe9SWxEkm718R89mLgTAo3cFu7i9kUWy59uYzPmw/SNhiWTVovdhif4yYFBHisscOWMJb/xCSDLrokchnAsvLMAQQ3VZ1FVYaxNO8OMbjAjN6ydhFxd8u6mG5QULcY+8D6yJ1tEPBz/TBNLbZp3Zb8ZqRxp6NUneUy7Zm4ZFsrDfTX0OExjtELkcE59FrKxTbsNKe0oLiY1l3baxzFf8pNr7oTFKDzEtI1yzk7ykJEMPCLPJRKtqqr0dJixkr+bhM1OIz7oe6eXRxG8y5dGf51sgc328bLsG7YZ7ZHhhHvh8SXL0ij1MQWXQtR4kBAchqVzz6rynIRpNU5aQZHvKJntq/DLtX9em020iLuKDHhIWmYeGjaXpQmYDLnSUCZTAsWX295A3R7R2ShhBY5FmvWHBrY7oNBTYDzz2oaFxUykQWy7ZlXYyDrfjNpadhfkWajbpnX+lH90=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
